# 7_78 단위 테스트

## 단위테스트
단위 테스트는 각 함수 정의가 정상적으로 동작하는 지 확인할 수 있는 방법  
기본적으로 Nothing 으로 처리 (Exception 은 프로그램이 정지되지 않지만 Nothing 은 정지 )
책에서 깊게 다루지 않고 JUnit5 등의 라이브러리를 소개하는 장으로 가볍게 소개 됨  

### 우리가 쓸 단위 테스트의 DI
```kotlin
implementation(kotlin("test"))
```
```kotlin
import kotlin.test.assertEquals
import kotlin.test.assertFails
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

fun fortyTwo() = 42

fun testFortyTwo(n: Int = 42) {
    assertEquals(
        expected = n,
        actual = fortyTwo(),
        message = "Incorrect, "
    )
}

fun allGood(b: Boolean = true) = b

fun testAllGood(b: Boolean = true) {
    assertTrue(allGood(b), "Not good")
}

fun <T> expect(
    expected: T,
    message: String?,
    block: () -> T
) {
    assertEquals(expected, block(), message)
}

fun testFortyTwo2(n: Int = 42) {
    expect(n, "Incorrect,") {fortyTwo()}
}

fun main() {
    testFortyTwo()
    testAllGood()

//    try {
//        testFortyTwo(43)
//    } catch (e: Exception){
//        e.printStackTrace()
//    }
//
//    try {
//        testAllGood(false)
//    } catch (e: Exception){
//        e.printStackTrace()
//    }

    testFortyTwo2()

//    try {
//        testFortyTwo2(43)
//    } catch (e: Exception){
//        e.printStackTrace()
//    }

    assertFails{ testFortyTwo2(43) }
//
//    try {
//        assertFails{ testFortyTwo2() }
//    } catch(e: Exception) {
//        e.printStackTrace()
//    }

    assertFailsWith<AssertionError> {
        testFortyTwo2(43)
    }

    try {
        assertFailsWith<AssertionError> {
            testFortyTwo2()
        }
    } catch (e: Exception) {
        e.printStackTrace()
    }

}
== result
Exception in thread "main" java.lang.AssertionError: Expected an exception of class java.lang.AssertionError to be thrown, but was completed successfully.
at kotlin.test.DefaultAsserter.fail(DefaultAsserter.kt:16)
at kotlin.test.AssertionsKt__AssertionsImplKt.checkResultIsFailure(AssertionsImpl.kt:22)
at kotlin.test.AssertionsKt.checkResultIsFailure(Unknown Source)
at _6_78_UnitTestKt.main(6_78_UnitTest.kt:71)
at _6_78_UnitTestKt.main(6_78_UnitTest.kt)
```